#!/usr/bin/env lua
--[[--------------------------------------------------------------------------
  tools/bundle.lua — build a single self-contained autorun script from src/.

  WHY A BUNDLE IS NEEDED
  ----------------------
  The trainer is written as modules, but REFramework cannot reliably load them
  as modules. The reasons, all verified against the user's own install:

    1. There is NO filesystem API in this REFramework build. fs.* is absent from
       the installed dinput8.dll, so a script cannot work out its own directory
       in order to build an absolute path.

    2. There is no game-directory accessor either. get_game_directory,
       get_module_path, get_working_directory — all absent. So `dofile` with a
       computed path is not available.

    3. require() depends on package.path. The DLL's embedded default is
       "!\lua\?.lua;!\lua\?\init.lua;!\?.lua;!\?\init.lua;...;.\?.lua;.\?\init.lua",
       which resolves against the process working directory. Whether that
       happens to include the autorun folder is not something we can rely on,
       and a wrong guess means every module silently fails to load.

    4. ScriptRunner globs *.lua in the autorun folder. Dropping fifteen module
       files in there means fifteen files each get executed as top-level
       scripts, which is not what a module file expects.

  The fix is package.preload. Lua's require() consults package.loaded, then
  package.preload, BEFORE any path-based searcher runs. If we register every
  module in package.preload, then require("re7trainer.logger") resolves
  correctly regardless of package.path, the working directory, or where the
  file was loaded from.

  That is what this script generates: one file, containing one
  package.preload entry per module, followed by the entry point. It has no
  path dependencies at all, which is the only way to make this robust when we
  cannot test in the target environment.

  USAGE
  -----
      lua tools/bundle.lua <src_dir> <output_file>

  Modules are emitted in arbitrary order deliberately: because require() is
  lazy, every preload entry is registered before the entry point runs, so no
  dependency ordering is required and the bundle cannot be broken by adding a
  module in the wrong place.
----------------------------------------------------------------------------]]

local src_dir = arg[1] or "src"
local out_path = arg[2] or "build/re7trainer.lua"

local MODULE_PREFIX = "re7trainer"

-- ---------------------------------------------------------------------------
-- Collect module files
-- ---------------------------------------------------------------------------

--- Run a command and capture its output.
local function capture(cmd)
  local pipe = io.popen(cmd)
  if pipe == nil then
    return nil
  end
  local output = pipe:read("*a")
  pipe:close()
  return output
end

--- Recursively list .lua files under a directory.
local function list_lua_files(root)
  local files = {}
  local listing = capture(string.format("find %q -name '*.lua' -type f | sort", root))
  if listing == nil then
    return files
  end

  for line in listing:gmatch("[^\n]+") do
    files[#files + 1] = line
  end
  return files
end

--- Map a source path to its module name.
-- src/logger.lua                 -> re7trainer.logger
-- src/utils/safe_call.lua        -> re7trainer.utils.safe_call
-- src/main.lua                   -> re7trainer.main
local function module_name_for(path, root)
  local relative = path:sub(#root + 2)          -- strip "<root>/"
  relative = relative:gsub("%.lua$", "")        -- strip extension
  relative = relative:gsub("/", ".")            -- path separators to dots
  return MODULE_PREFIX .. "." .. relative
end

--- Read a whole file, or nil.
local function read_file(path)
  local handle = io.open(path, "rb")
  if handle == nil then
    return nil
  end
  local contents = handle:read("*a")
  handle:close()
  return contents
end

-- ---------------------------------------------------------------------------
-- Emit
-- ---------------------------------------------------------------------------

local files = list_lua_files(src_dir)
if #files == 0 then
  io.stderr:write("bundle: no .lua files found under " .. src_dir .. "\n")
  os.exit(1)
end

-- Ensure the output directory exists.
local out_dir = out_path:match("^(.*)/[^/]+$")
if out_dir ~= nil and out_dir ~= "" then
  os.execute(string.format("mkdir -p %q", out_dir))
end

local out = io.open(out_path, "wb")
if out == nil then
  io.stderr:write("bundle: cannot write " .. out_path .. "\n")
  os.exit(1)
end

out:write("--[[--------------------------------------------------------------------------\n")
out:write("  RE7 Personal Trainer - generated bundle. DO NOT EDIT.\n\n")
out:write("  Generated by tools/bundle.lua from the modules in src/.\n")
out:write("  Edit the files in src/ and re-run tools/install.sh instead.\n\n")
out:write("  Each module is registered in package.preload, which Lua's require()\n")
out:write("  consults before any path-based searcher. This makes module resolution\n")
out:write("  independent of package.path, the working directory, and the location\n")
out:write("  the bundle was loaded from - none of which are knowable from inside a\n")
out:write("  script in this REFramework build.\n")
out:write("----------------------------------------------------------------------------]]\n\n")

local emitted = {}
local entry_module = nil

for _, path in ipairs(files) do
  local name = module_name_for(path, src_dir)
  local contents = read_file(path)

  if contents == nil then
    io.stderr:write("bundle: cannot read " .. path .. "\n")
    os.exit(1)
  end

  emitted[#emitted + 1] = name
  if name == MODULE_PREFIX .. ".main" then
    entry_module = name
  end

  out:write(string.format("-- ---- %s  (from %s)\n", name, path))
  out:write(string.format("package.preload[%q] = function()\n", name))
  out:write(contents)

  -- A module file that does not end in a newline would run its last statement
  -- into the closing "end"; guard the boundary explicitly.
  if contents:sub(-1) ~= "\n" then
    out:write("\n")
  end

  out:write("end\n\n")
end

if entry_module == nil then
  io.stderr:write("bundle: no main module found (expected " .. MODULE_PREFIX .. ".main)\n")
  out:close()
  os.exit(1)
end

out:write("-- ---- entry point\n")
out:write(string.format("return require(%q)\n", entry_module))
out:close()

io.stderr:write(string.format("bundle: wrote %s (%d modules)\n", out_path, #emitted))
